config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todo.urls"))
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path("", views.index, name="index"),
    path("single/<int:pk>/", views.single, name="single"),
    path("delete/<int:pk>/", views.delete, name="delete"),
    path("edit/<int:pk>/", views.edit, name="edit"),
    path("done/<int:pk>/", views.done, name="done"),

]

todo/models.py
from django.db import models

# Create your models here.      モデルを編集したら　マイグレーションが必要
class Todo(models.Model):    # フィールドを作る   id は自動的に振られる。

    content = models.CharField(max_length=100)
    
    deadline = models.DateField()

    done = models.BooleanField(default=False)    # やったかどうかの記録（フィールド入力必須 null 禁止）

todo/forms.py
from django import forms        # デフォルトで forms.py は無いのでアプリフォルダ以下に作成する。
from .models import Todo

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ["content", "deadline"]     # バリデーション対象

todo/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Todo
from .forms import TodoForm
from django.contrib import messages

# Create your views here.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        todos = Todo.objects.all()
        context = { "todos": todos}    # todos の中には複数データが入っている

        return render(request, "todo/index.html", context)   # template 以下を読む （setting.py で指定している）
    
    def post(self, request, *args, **kwargs):
        """
        todo = Todo(content=request.POST["content"], deadline=request.POST["deadline"])   バリデーションチェックされてない
        todo.save()
        """
        form = TodoForm(request.POST)        # 継承する forms.ModelForm に取る引数の情報が設定されている
        if form.is_valid():                  # models → views の間に forms を挟む感じ
            form.save()
        else:
            print(form.errors)
            messages.error(request, form.errors)


        return redirect("todo:index")


index = IndexView.as_view()

# 個別表示のビュー
class Singleview(View):
    def get(self, request, pk, *args, **kwargs):
        
        todo = Todo.objects.filter(id=pk).first()    # 配列で取ってくるので、１個でも first が必要、 無いと for ループを回す必要がある
        context ={ "todo":todo }

        return render(request, "todo/single.html", context)


single = Singleview.as_view()
        

# 削除のビュー       
class DeleteView(View):
    def post(self, request, pk, *args, **kwargs):
        print("削除")
        print(pk)

        todo = Todo.objects.filter(id=pk).first()
        todo.delete()

        return redirect("todo:index")

delete = DeleteView.as_view()



class EditView(View):

    def post(self, request, pk, *args, **kwargs): #  pk 編集対象のid
        print("編集")
        print(pk)

        todo = Todo.objects.filter(id=pk).first()   # 編集対象のTodoを特定する

        form = TodoForm(request.POST, instance=todo) # instance に編集対象の Todo を指定
        
        if form.is_valid():                  # models → views の間に forms を挟む感じ
            form.save()
        else:
            print(form.errors)
            messages.error(request, form.errors)

        return redirect("todo:index")

edit = EditView.as_view()

# Todo の完了、未完を切り替えるビュー
class Doneview(View):
    def post(self, request, pk, *args, **kwargs): #  pk 編集対象のid
        print("切り替え")
        todo = Todo.objects.filter(id=pk).first() 
        # todo.done = True                           # バリデーションは不要

        todo.done = not todo.done                    # デフォルトで False なので、ボタンを押すと True になる

        todo.save()

        return redirect("todo:index")
    
done = Doneview.as_view()

templates/todo/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>todo list</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">                                             
               {# boot strap を導入する#}
<style>
    .todo_edit_chk {
        display: none;
    }
    .todo_edit_area {
        display: none;
    }
    .todo_edit_chk:checked ~ .todo_edit_area {    
        display: block;
    }
    .todo_edit_chk:checked ~ .todo_area {    
        display: none;
    }

</style>

</head>
<body>
    <main class="container">
   
        {% for message in messages %}
        <div>{{ message }}</div>
        {% endfor %}
        
        <form action ="" method="post">        {# 転送先はデフォルトでは views.py になる#}
            {% csrf_token %}
            <div>                                {# ← div に入れるとブロック要素になる #}
                <input type="date" name="deadline">
            </div>
            <div>
                <textarea class="form-control" name="content"></textarea>
            </div>
            <div>
                <input class="btn btn-primary" type="submit" value="post">
            </div>       
        </form>
              
                  {# todos は model オブジェクト　辞書型のリストのように使える #} 
        
        {% for todo in todos %}
        <div class="border my-2 p-2">
            <input id="todo_edit_chk_{{ todo.id }}" class="todo_edit_chk" type="checkbox">

            

            <div class="todo_area">
                <div>{{ todo.deadline }}</div>
                <div>{{ todo.content }}</div>
            </div>

            <form class="todo_edit_area" action="{% url 'todo:edit' todo.id %}" method="post">      {#  #} 
                {% csrf_token %}
                <div>                               
                    <input type="date" name="deadline" value="{{ todo.deadline|date:'Y-m-d'}}">
                </div>
                <div>
                    <textarea class="form-control" name="content">{{ todo.content }}</textarea>
                </div>
                <div>
                    <input class="btn btn-primary" type="submit" value="編集">
                </div> 


            </form>

            <div class="text-end">

                <form action="{% url 'todo:done' todo.id %}" method="POST" style="display: inline-block;">
                    {% csrf_token %}
                    {% if todo.done %}
                    <input class="btn btn-primary" type="submit" value="未完にする">
                    {% else %}
                    <input class="btn btn-outline-primary" type="submit" value="完了にする">
                    {% endif %}
                </form>
                

                <label class="btn btn-success" for="todo_edit_chk_{{ todo.id }}">編集</label>

                                                                                                            {# 削除確認のダイアログ表示 HTMLの属性の一部で javascript 発動されるものがある #}
                <form action="{% url 'todo:delete' todo.id %}" method="POST" style="display: inline-block; "onsubmit="if(confirm('本当に削除しますか？')){ return true } else { return false };">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="削除">
                </form>

                <a href="{% url 'todo:single' todo.id %}"> 個別ページ </a>
            </div>

        </div>
        {% endfor %}
            
    </main>
</body>
</html>

templates/todo/single.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>個別ページ</h1>

    <h2>{{ todo.id }} : {{ todo.content }}</h2>
    <div>{{ todo.deadline }}</div>

</body>
</html>